sentinelgarbage/config/routes.rb
Rails.application.routes.draw do
  resources :noticia
  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'
  get 'Pagenoticias',to:'pgnoticia#index'
  get 'Pagereciclaje',to:'pgreciclaje#index'
  get 'Pagecentroinfo',to:'pgcentroinfo#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sentinelgarbage/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

sentinelgarbage/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sentinelgarbage/app/models/noticium.rb
class Noticium < ApplicationRecord
end

sentinelgarbage/app/models/user.rb
class User < ApplicationRecord
end

sentinelgarbage/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

sentinelgarbage/app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
end 
end

sentinelgarbage/app/controllers/noticia_controller.rb
class NoticiaController < InheritedResources::Base

  private

    def noticium_params
      params.require(:noticium).permit(:titulo, :nombre, :descripcion, :fecha, :infoOrigen)
    end
end

sentinelgarbage/app/controllers/pgcentroinfo_controller.rb
class PgcentroinfoController < ApplicationController
    def index
        
    end
end

sentinelgarbage/app/controllers/pgnoticia_controller.rb
class PgnoticiaController < ApplicationController
   def index
      @noticias=Noticium.all
   end
end

sentinelgarbage/app/controllers/pgreciclaje_controller.rb
class PgreciclajeController < ApplicationController
    def index
    end
end

sentinelgarbage/app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  private

    def user_params
      params.require(:user).permit(:name, :email, :telephone, :adress)
    end
end

sentinelgarbage/app/helpers/application_helper.rb
module ApplicationHelper
end

sentinelgarbage/app/helpers/home_helper.rb
module HomeHelper
end

sentinelgarbage/app/helpers/noticia_helper.rb
module NoticiaHelper
end

sentinelgarbage/app/helpers/pgcentroinfo_helper.rb
module PgcentroinfoHelper
end

sentinelgarbage/app/helpers/pgnoticia_helper.rb
module PgnoticiaHelper
end

sentinelgarbage/app/helpers/pgreciclaje_helper.rb
module PgreciclajeHelper
end

sentinelgarbage/app/helpers/users_helper.rb
module UsersHelper
end

sentinelgarbage/app/views/home/index.html.erb
<div class="container">
<div class="spaceVertical"></div>
<div class="row">
        <div class="col-lg-4 mb-4">
          <div class="card h-100">
            <h4 class="card-header">Noticias</h4>
            <div class="card-body">
              <%= image_tag('Noti1.jpg', :class =>"img-thumbnail", :width=>"70%",:height=>"70%") %>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
            </div>
            <div class="card-footer">
              <%= link_to 'Leer más','/Pagenoticias', {:class => "buttonPanel"} %>
            </div>
          </div>
        </div>
        <div class="col-lg-4 mb-4">
          <div class="card h-100">
            <h4 class="card-header">Reciclaje</h4>
            <div class="card-body">
               <%= image_tag('reciclaje.jpg', :class =>"img-thumbnail", :width=>"70%",:height=>"70%") %>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis ipsam eos, nam perspiciatis natus commodi similique totam consectetur praesentium molestiae </p>
            </div>
            <div class="card-footer">
               <%= link_to 'Leer más','/Pagereciclaje', {:class => "buttonPanel"} %>
            </div>
          </div>
        </div>
        <div class="col-lg-4 mb-4">
          <div class="card h-100">
            <h4 class="card-header">Centros de información</h4>
            <div class="card-body">
            <%= image_tag('centroInfo.jpg', :class =>"img-thumbnail", :width=>"70%",:height=>"70%") %>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
            </div>
            <div class="card-footer">
              <%= link_to 'Leer más','/Pagecentroinfo', {:class => "buttonPanel"} %>
            </div>
          </div>
        </div>
      </div>
      <%= image_tag('mapa.jpg', :class =>"img-fluid rounded mb-4") %>
</div>

sentinelgarbage/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sentinelgarbage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- Barra de navegacion -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">  
<div class="space">  
   <%= link_to image_tag('logo.png', :class =>"logoSentinela") %>
 </div> 
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Principal','/', {:class => "nav-link"} %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Noticias</a>
      </li>    
      <li class="nav-item">
        <a class="nav-link" href="#">Reciclaje</a>
      </li> 
      <li class="nav-item">
        <a class="nav-link" href="#">Centros de atención</a>
      </li>             
    </ul>     
    <form class="form-inline my-2 my-lg-0">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to 'Log-in','/admin/login', {:class => "nav-link"} %>
      </li>  
    </ul> 
      <input class="form-control mr-sm-2" type="search" placeholder="buscar" aria-label="Buscar">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>
    
  </div>
</nav>
    <%= yield %>
     <footer class="py-4 bg-light">
      <div class="container">
        <p class="m-0 text-center text-green">Copyright &copy; SentinelaGarbage 2018</p>
      </div>
      <!-- /.container -->
    </footer>
  </body>
</html>

sentinelgarbage/app/views/noticia/_form.html.erb
<%= form_with(model: noticium, local: true) do |form| %>
  <% if noticium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(noticium.errors.count, "error") %> prohibited this noticium from being saved:</h2>

      <ul>
      <% noticium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.datetime_select :fecha %>
  </div>

  <div class="field">
    <%= form.label :infoOrigen %>
    <%= form.text_field :infoOrigen %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sentinelgarbage/app/views/noticia/edit.html.erb
<h1>Editing Noticium</h1>

<%= render 'form', noticium: @noticium %>

<%= link_to 'Show', @noticium %> |
<%= link_to 'Back', noticia_path %>

sentinelgarbage/app/views/noticia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Noticia</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Fecha</th>
      <th>Infoorigen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @noticia.each do |noticium| %>
      <tr>
        <td><%= noticium.titulo %></td>
        <td><%= noticium.nombre %></td>
        <td><%= noticium.descripcion %></td>
        <td><%= noticium.fecha %></td>
        <td><%= noticium.infoOrigen %></td>
        <td><%= link_to 'Show', noticium %></td>
        <td><%= link_to 'Edit', edit_noticium_path(noticium) %></td>
        <td><%= link_to 'Destroy', noticium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Noticium', new_noticium_path %>

sentinelgarbage/app/views/noticia/new.html.erb
<h1>New Noticium</h1>

<%= render 'form', noticium: @noticium %>

<%= link_to 'Back', noticia_path %>

sentinelgarbage/app/views/noticia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @noticium.titulo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @noticium.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @noticium.descripcion %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @noticium.fecha %>
</p>

<p>
  <strong>Infoorigen:</strong>
  <%= @noticium.infoOrigen %>
</p>

<%= link_to 'Edit', edit_noticium_path(@noticium) %> |
<%= link_to 'Back', noticia_path %>

sentinelgarbage/app/views/pgcentroinfo/index.html.erb
<h1>centros informacion</h1>

sentinelgarbage/app/views/pgnoticia/index.html.erb
<div class="container">
<h1 class="mt-4 mb-3">Noticias</h1>
  <div class="row">
  <% @noticias.each do |noticia| %>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">              
                <a href="#" class="tituloNoticia"><%= noticia.titulo%></a>
              </h4>
              <p class="card-text"><%= noticia.descripcion%></p>
            </div>
          </div>
        </div>       
  <% end%>
    </div>  
    <div class="spaceVertical"></div>
</div>
    
   

sentinelgarbage/app/views/pgreciclaje/index.html.erb
<h1>Reciclaje</h1>

sentinelgarbage/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone %>
  </div>

  <div class="field">
    <%= form.label :adress %>
    <%= form.text_field :adress %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sentinelgarbage/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

sentinelgarbage/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Telephone</th>
      <th>Adress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.telephone %></td>
        <td><%= user.adress %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

sentinelgarbage/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

sentinelgarbage/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @user.telephone %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @user.adress %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>